# Generated by Django 4.2.4 on 2023-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_prettynum_alter_userinfo_depart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
    ]
